---
- name: Install key signing helm repo
  apt_key:
    url: "https://baltocdn.com/helm/signing.asc"
    state: present

- name: Add repository for install Helm
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
    filename: 'helm-stable-debian.list'

- name: Install Helm package
  apt:
    name:
      - helm
    state: present
