--- 
- name: Download AWS CLI
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp
    remote_src: True

- name: Install AWS CLI
  shell: |
    cd /tmp/aws
    ./install --update
